[package]
name = "subversive"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14", features = ["dynamic_linking"] }
bevy_rapier2d = "0.27"
bevy_asset_loader = "0.21"
serde = { version = "1.0", features = ["derive"] }
ron = "0.8"
rand = "0.8"
leafwing-input-manager = "0.14"

[features]
default = ["bevy/default"]
dev = ["bevy/dynamic_linking"]

# Enable fast compiles for development
[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3